= Neue Organisation anlegen
:page-layout: docs
:toc: macro
:toclevels: 2

include::_partials/aktueller-vertrag.adoc[]

toc::[]

== Ziel

Eine neue Organisation soll im Themenrepo so angelegt werden, dass das Jenkins-Plugin sie beim nächsten Seed-Lauf erkennt und daraus einen Jenkins-Job generiert.

== Minimaler Ablauf

. Organisationsordner anlegen.
. `gretl-datenportal-job.yaml` erstellen.
. `build.gradle` erstellen.
. Mindestens einen Datensatzordner mit genau einer `.xtf`- oder `.xml`-Datenblattdatei anlegen.
. Änderungen committen.
. Seed-Job in Jenkins ausführen.

== Beispielstruktur

[source,text]
----
neue-org/
  build.gradle
  gretl-datenportal-job.yaml
  ch.so.neueorg.beispiel/
    ch.so.neueorg.beispiel.xtf
----

== Minimale `gretl-datenportal-job.yaml`

[source,yaml]
----
title: Neue Organisation
description: Publikationsjobs für die neue Organisation.

permissions:
  read:
    - team: datenportal-read
  build:
    - team: neue-org-build
----

== Minimales `build.gradle`

[source,groovy]
----
plugins {
    id 'ch.so.agi.gretl'
}

apply from: '../shared/gradle/organisation-common.gradle'
----

== Was automatisch passiert

Nach einem erfolgreichen Seed-Lauf:

* wird die Organisation vom Plugin erkannt;
* wird ein Jenkins-Job erzeugt oder aktualisiert;
* erscheinen die erkannten Datensätze im Startformular;
* greifen die gesetzten Lese- und Build-Berechtigungen.

== Was nicht automatisch passiert

Ohne Seed-Lauf erscheint die Organisation nicht als generierter Jenkins-Job. Ohne gültige Berechtigungen wird die Organisation als ungültig behandelt. Ohne `build.gradle` kann die Pipeline nicht ausgeführt werden.

== Weiterführend

* Wie der Seed-Lauf diese neue Organisation scannt und materialisiert, ist im Repository link:https://codeberg.org/edigonzales/jenkins-gretl-datenportal-plugin[jenkins-gretl-datenportal-plugin] beschrieben.
* Wie lokaler Bootstrap und Jenkins-Restart für Tests funktionieren, ist im Repository link:https://codeberg.org/edigonzales/datenportal-jenkins-dev[datenportal-jenkins-dev] beschrieben.
