baseUri=https://data.so.ch
downloadBase=https://s3.geo.so.ch/datenportal
publisher=ch.so.agi
title=Datenportal Kanton Solothurn
description=Datensätze und Datenserien des Kantons Solothurn
theme.Arbeit_Erwerb=http://publications.europa.eu/resource/authority/data-theme/ECON
theme.Bau_und_Wohnungswesen=http://publications.europa.eu/resource/authority/data-theme/REGI
theme.Bevoelkerung=http://publications.europa.eu/resource/authority/data-theme/SOCI
theme.Bildung_Wissenschaft=http://publications.europa.eu/resource/authority/data-theme/EDUC
theme.Energie=http://publications.europa.eu/resource/authority/data-theme/ENER
theme.Finanzen=http://publications.europa.eu/resource/authority/data-theme/ECON
theme.Geografie=http://publications.europa.eu/resource/authority/data-theme/REGI
theme.Gesetzgebung=http://publications.europa.eu/resource/authority/data-theme/JUST
theme.Gesundheit=http://publications.europa.eu/resource/authority/data-theme/HEAL
theme.Handel=http://publications.europa.eu/resource/authority/data-theme/ECON
theme.Industrie_und_Dienstleistungen=http://publications.europa.eu/resource/authority/data-theme/ECON
theme.Kriminalitaet_Strafrecht=http://publications.europa.eu/resource/authority/data-theme/JUST
theme.Kultur_Medien_Informationsgesellschaft_Sport=http://publications.europa.eu/resource/authority/data-theme/EDUC
theme.Landwirtschaft_Forstwirtschaft=http://publications.europa.eu/resource/authority/data-theme/AGRI
theme.Mobilitaet_und_Verkehr=http://publications.europa.eu/resource/authority/data-theme/TRAN
theme.Oeffentliche_Ordnung_und_Sicherheit=http://publications.europa.eu/resource/authority/data-theme/JUST
theme.Politik=http://publications.europa.eu/resource/authority/data-theme/GOVE
theme.Preise=http://publications.europa.eu/resource/authority/data-theme/ECON
theme.Raum_und_Umwelt=http://publications.europa.eu/resource/authority/data-theme/ENVI
theme.Soziale_Sicherheit=http://publications.europa.eu/resource/authority/data-theme/SOCI
theme.Statistische_Grundlagen=http://publications.europa.eu/resource/authority/data-theme/SOCI
theme.Tourismus=http://publications.europa.eu/resource/authority/data-theme/ECON
theme.Verwaltung=http://publications.europa.eu/resource/authority/data-theme/GOVE
theme.Volkswirtschaft=http://publications.europa.eu/resource/authority/data-theme/ECON
frequency.continual=http://publications.europa.eu/resource/authority/frequency/CONT
frequency.daily=http://publications.europa.eu/resource/authority/frequency/DAILY
frequency.weekly=http://publications.europa.eu/resource/authority/frequency/WEEKLY
frequency.biweekly=http://publications.europa.eu/resource/authority/frequency/BIWEEKLY
frequency.monthly=http://publications.europa.eu/resource/authority/frequency/MONTHLY
frequency.quarterly=http://publications.europa.eu/resource/authority/frequency/QUARTERLY
frequency.biannually=http://publications.europa.eu/resource/authority/frequency/ANNUAL_2
frequency.annually=http://publications.europa.eu/resource/authority/frequency/ANNUAL
frequency.asNeeded=http://publications.europa.eu/resource/authority/frequency/AS_NEEDED
frequency.irregular=http://publications.europa.eu/resource/authority/frequency/IRREG
frequency.notPlanned=http://publications.europa.eu/resource/authority/frequency/NEVER
frequency.unknown=http://publications.europa.eu/resource/authority/frequency/UNKNOWN
access.open=http://publications.europa.eu/resource/authority/access-right/PUBLIC
access.public_with_conditions=http://publications.europa.eu/resource/authority/access-right/PUBLIC
access.restricted=http://publications.europa.eu/resource/authority/access-right/RESTRICTED
access.internal=http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC
access.confidental=http://publications.europa.eu/resource/authority/access-right/NON_PUBLIC
datasetPath=/datasets/
seriesPath=/series/
issuePath=/issues/
