datenportal.plugin.gretl.id=ch.so.agi.gretl
datenportal.plugin.gretl.version=5.0.0-SNAPSHOT
datenportal.plugin.download.id=de.undercouch.download
datenportal.plugin.download.version=5.6.0
datenportal.plugin.ssh.id=org.hidetake.ssh
datenportal.plugin.ssh.version=2.10.1

datenportal.repository.project.1=https://jars.interlis.guru/snapshots
datenportal.repository.project.2=https://jars.interlis.guru/mirror
datenportal.repository.project.3=https://jars.interlis.ch
datenportal.repository.project.4=https://repo.osgeo.org/repository/release/
datenportal.repository.project.5=https://maven.geo-solutions.it
datenportal.repository.project.6=https://plugins.gradle.org/m2/

datenportal.repository.plugin.1=https://jars.interlis.guru/snapshots
datenportal.repository.plugin.2=https://jars.interlis.guru/mirror
datenportal.repository.plugin.3=https://plugins.gradle.org/m2/

datenportal.offline.seed.1=ch.so.agi:gretl-core:5.0.0-SNAPSHOT
datenportal.offline.seed.2=de.undercouch:gradle-download-task:5.6.0
datenportal.offline.seed.3=org.hidetake:gradle-ssh-plugin:2.10.1
